/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.IOException;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import dao.BaseDAO;
import dao.CasalDAO;
import dao.CasalDAOImp;
import dao.PessoaDAO;
import dao.PessoaDAOImp;
import entity.Casal;
import entity.Pessoa;

/**
 *
 * @author raquelmelo
 */
public class CadastroCasal extends javax.swing.JFrame {

	/**
	 * Creates new form Tela2
	 */
	public CadastroCasal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		p_cadastro = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		jSeparator5 = new javax.swing.JSeparator();
		jTextField_nDela = new javax.swing.JTextField();
		jTextField_casal = new javax.swing.JTextField();
		jTextField_nDele = new javax.swing.JTextField();
		jTextField_tel1 = new javax.swing.JTextField();
		jTextField_email = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea_ender = new javax.swing.JTextArea();
		jSeparator6 = new javax.swing.JSeparator();
		jButton_cadastrar = new javax.swing.JButton();
		jTextField_tel2 = new javax.swing.JTextField();
		jSeparator7 = new javax.swing.JSeparator();
		jLabel11 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(27, 187, 125));

		jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("CADASTRO");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel1MouseEntered(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(196, 196, 196)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE).addGap(25, 25,
								25)));

		jLabel5.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel5.setText("Nome dela:");

		jLabel6.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel6.setText("Nome dele:");

		jLabel7.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel7.setText("Nome do Casal:");

		jLabel8.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel8.setText("E-mail:");

		jLabel9.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel9.setText("End. Residencial:");

		jLabel10.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel10.setText("Telefone:");

		jSeparator1.setBackground(new java.awt.Color(254, 254, 254));

		jSeparator2.setBackground(new java.awt.Color(254, 254, 254));

		jSeparator3.setBackground(new java.awt.Color(254, 254, 254));

		jSeparator4.setBackground(new java.awt.Color(254, 254, 254));
		jSeparator4.setPreferredSize(new java.awt.Dimension(5, 6));

		jSeparator5.setBackground(new java.awt.Color(254, 254, 254));

		jTextField_nDela.setToolTipText("Nome Completo");
		jTextField_nDela.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_nDelaActionPerformed(evt);
			}
		});

		jTextField_casal.setToolTipText("Apelido do Casal");

		jTextField_nDele.setToolTipText("Nome Completo");

		jTextField_tel1.setToolTipText("Telefone para Contato");

		jTextField_email.setToolTipText("E-mail para Contato");

		jTextArea_ender.setColumns(20);
		jTextArea_ender.setLineWrap(true);
		jTextArea_ender.setRows(5);
		jTextArea_ender.setToolTipText("Insira Bairro, Rua e Endereço da Residência");
		jScrollPane2.setViewportView(jTextArea_ender);

		jSeparator6.setBackground(new java.awt.Color(254, 254, 254));

		jButton_cadastrar.setText("Cadastrar");
		jButton_cadastrar.setToolTipText("Confirmar Cadastro");
		jButton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_cadastrarActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jTextField_tel2.setToolTipText("Telefone para Contato");

		jSeparator7.setBackground(new java.awt.Color(254, 254, 254));

		jLabel11.setFont(new java.awt.Font("Baekmuk Batang", 1, 18)); // NOI18N
		jLabel11.setText("Telefone 2:");

		javax.swing.GroupLayout p_cadastroLayout = new javax.swing.GroupLayout(p_cadastro);
		p_cadastro.setLayout(p_cadastroLayout);
		p_cadastroLayout.setHorizontalGroup(p_cadastroLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(p_cadastroLayout.createSequentialGroup().addGap(22, 22, 22)
						.addGroup(p_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_nDela, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_casal, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(p_cadastroLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel5).addComponent(jLabel7).addComponent(jLabel9)
										.addGroup(p_cadastroLayout.createSequentialGroup().addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel10)
												.addComponent(jTextField_tel1, javax.swing.GroupLayout.PREFERRED_SIZE,
														304, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jSeparator1))
										.addComponent(jSeparator5).addComponent(jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE, 304,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(111, 111, 111)
						.addGroup(
								p_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel6).addComponent(jLabel8)
										.addGroup(p_cadastroLayout.createSequentialGroup().addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel11).addComponent(jTextField_tel2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 304,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jTextField_nDele, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE,
														143, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		p_cadastroLayout
				.setVerticalGroup(
						p_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(p_cadastroLayout
										.createSequentialGroup().addContainerGap().addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(p_cadastroLayout.createSequentialGroup().addComponent(
														jLabel6).addGap(1, 1, 1)
														.addComponent(jTextField_nDele,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(p_cadastroLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jSeparator4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 10,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(p_cadastroLayout.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jLabel11)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jTextField_tel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(1, 1, 1).addComponent(jSeparator7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				10,
																				javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(p_cadastroLayout.createSequentialGroup().addComponent(jLabel5)
														.addGap(1, 1, 1)
														.addComponent(
																jTextField_nDela,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(p_cadastroLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jSeparator1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 10,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(p_cadastroLayout.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jLabel10)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jTextField_tel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(1, 1, 1).addComponent(jSeparator2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				10,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														p_cadastroLayout.createSequentialGroup().addComponent(jLabel7)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextField_casal,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(1, 1, 1).addComponent(jSeparator5,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 10,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														p_cadastroLayout.createSequentialGroup().addComponent(jLabel8)
																.addGap(9, 9, 9)
																.addComponent(jTextField_email,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(0, 0, 0)
																.addComponent(jSeparator3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 10,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(18, 18, 18)
										.addGroup(p_cadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(p_cadastroLayout.createSequentialGroup().addComponent(jLabel9)
														.addGap(9, 9, 9)
														.addComponent(jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE, 107,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(8, 8, 8))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														p_cadastroLayout.createSequentialGroup()
																.addComponent(jButton_cadastrar,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 59,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(31, 31, 31)))
										.addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(p_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 772,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(p_cadastro,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseEntered
		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel1MouseEntered

	private void jTextField_nDelaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_nDelaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_nDelaActionPerformed

	private void jButton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_jButton_cadastrarActionPerformed
		String nDela, nDele, nCasal, tel1, tel2, endereco;
		nDela = jTextField_nDela.getText();
		nDele = jTextField_nDele.getText();
		tel1 = jTextField_tel1.getText();
		tel2 = jTextField_tel2.getText();
		endereco = jTextArea_ender.getText();
		nCasal = jTextField_casal.getText();
		if (nDela.equals("") || nDele.equals("") || tel1.equals("") || tel2.equals("") || endereco.equals("")
				|| nCasal.equals("")) {
			JOptionPane.showMessageDialog(null, "Preencha todos os campos");
		} else {
			Pessoa esposa = new Pessoa();
			esposa.setNome(nDela);
			esposa.setTelefone(tel2);

			Pessoa marido = new Pessoa();
			marido.setNome(nDele);
			marido.setTelefone(tel1);

			Casal casal = new Casal();
			casal.setEsposa(esposa);
			casal.setMarido(marido);
			casal.setEmail("");
			casal.setEndereco(endereco);
			casal.setNomeCasal(nCasal);
			BaseDAO base;
			try {
				base = new BaseDAO();
				CasalDAO casalDAO = new CasalDAOImp(base);
				PessoaDAO pessoaDAO =new PessoaDAOImp(base);
				pessoaDAO.create(esposa);
				esposa = pessoaDAO.buscarPorNome(esposa.getNome());
				pessoaDAO.create(marido);
				marido = pessoaDAO.buscarPorNome(marido.getNome());
				casalDAO.create(casal);
				casalDAO.getConnectionSource().close();
				dispose();
				JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
			} catch (SQLException e) {
				dispose();
				JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar salvar!");
				e.printStackTrace();
			}
			// envia esses dados pro banco!
		}
	}// GEN-LAST:event_jButton_cadastrarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadastroCasal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadastroCasal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadastroCasal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadastroCasal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadastroCasal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_cadastrar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JTextArea jTextArea_ender;
	private javax.swing.JTextField jTextField_casal;
	private javax.swing.JTextField jTextField_email;
	private javax.swing.JTextField jTextField_nDela;
	private javax.swing.JTextField jTextField_nDele;
	private javax.swing.JTextField jTextField_tel1;
	private javax.swing.JTextField jTextField_tel2;
	private javax.swing.JPanel p_cadastro;
	// End of variables declaration//GEN-END:variables
}
