/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import dao.BaseDAO;
import dao.PessoaDAO;
import dao.PessoaDAOImp;
import dao.TipoEquipeDAO;
import dao.TipoEquipeDAOImp;
import entity.Casal;
import entity.Encontro;
import entity.Equipe;
import entity.Pessoa;
import entity.TipoEquipe;

/**
 *
 * @author raquelmelo
 */
public class CadastroEncontros extends javax.swing.JFrame {

	/**
	 * Creates new form Tela2
	 */
	private Encontro encontro = new Encontro();

	public CadastroEncontros() throws SQLException, IOException {
		Date d = new Date();
		Calendar cal = new GregorianCalendar();
		cal.setTime(d);
		encontro.setAno(cal.YEAR);
		BaseDAO baseDAO = new BaseDAO();
		PessoaDAO pessoaDAO = new PessoaDAOImp(baseDAO);
		Pessoa oEspiritual = pessoaDAO.buscarPorId(5);
		encontro.setOrientadorEspiritual(oEspiritual);
		baseDAO.getConnection().close();
		initComponents();
		jTextField_padre.setText(encontro.getOrientadorEspiritual().getNomeUsual());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField_canto = new javax.swing.JTextField();
		jTextField_pos = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextField_financas = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		jTextField_montag = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		jTextField_circulo = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jTextField_visit = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jTextField_boa = new javax.swing.JTextField();
		jLabel26 = new javax.swing.JLabel();
		jTextField_apres = new javax.swing.JTextField();
		jTextField_secret = new javax.swing.JTextField();
		jLabel28 = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();
		jTextField_liturgia = new javax.swing.JTextField();
		jTextField_cafe = new javax.swing.JTextField();
		jLabel34 = new javax.swing.JLabel();
		jTextField_compras = new javax.swing.JTextField();
		jLabel33 = new javax.swing.JLabel();
		jTextField_ordem = new javax.swing.JTextField();
		jLabel31 = new javax.swing.JLabel();
		jLabel32 = new javax.swing.JLabel();
		jTextField_cozinha = new javax.swing.JTextField();
		jTextField_acolhida = new javax.swing.JTextField();
		jLabel23 = new javax.swing.JLabel();
		jTextField_vigilia = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jTextField_recep = new javax.swing.JTextField();
		jLabel35 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jTextField_padre = new javax.swing.JTextField();
		jTextField_ano = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jTextField_casalADM = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		jTextField_ficha = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(27, 187, 125));

		jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("REGISTRO DE ENCONTRO");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel1MouseEntered(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(98, 98, 98)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup().addGap(14, 14, 14)
										.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap()));

		jTextField_canto.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_cantoMouseClicked(evt);
			}
		});
		jTextField_canto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_cantoActionPerformed(evt);
			}
		});

		jTextField_pos.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_posMouseClicked(evt);
			}
		});
		jTextField_pos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_posActionPerformed(evt);
			}
		});

		jLabel18.setText("Compras");

		jTextField_financas.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_financasMouseClicked(evt);
			}
		});
		jTextField_financas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_financasActionPerformed(evt);
			}
		});

		jLabel25.setText("Visitação");

		jTextField_montag.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_montagMouseClicked(evt);
			}
		});
		jTextField_montag.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_montagActionPerformed(evt);
			}
		});

		jLabel22.setText("Circulo Estudo");

		jTextField_circulo.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_circuloMouseClicked(evt);
			}
		});
		jTextField_circulo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_circuloActionPerformed(evt);
			}
		});

		jLabel21.setText("Liturgia");

		jLabel20.setText("Mini Mercado e Café");

		jTextField_visit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_visitMouseClicked(evt);
			}
		});
		jTextField_visit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_visitActionPerformed(evt);
			}
		});

		jLabel19.setText("Cozinha");

		jTextField_boa.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_boaMouseClicked(evt);
			}
		});
		jTextField_boa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_boaActionPerformed(evt);
			}
		});

		jLabel26.setText("Ordem e Limpeza");

		jTextField_apres.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_apresMouseClicked(evt);
			}
		});
		jTextField_apres.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_apresActionPerformed(evt);
			}
		});

		jTextField_secret.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_secretMouseClicked(evt);
			}
		});
		jTextField_secret.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_secretActionPerformed(evt);
			}
		});

		jLabel28.setText("Vigilia na Comunidade");

		jLabel29.setText("Acolhida");

		jTextField_liturgia.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_liturgiaMouseClicked(evt);
			}
		});
		jTextField_liturgia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_liturgiaActionPerformed(evt);
			}
		});

		jTextField_cafe.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_cafeMouseClicked(evt);
			}
		});
		jTextField_cafe.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_cafeActionPerformed(evt);
			}
		});

		jLabel34.setText("Montagem e Palestra");

		jTextField_compras.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_comprasMouseClicked(evt);
			}
		});
		jTextField_compras.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_comprasActionPerformed(evt);
			}
		});

		jLabel33.setText("Pós Encontro");

		jTextField_ordem.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_ordemMouseClicked(evt);
			}
		});
		jTextField_ordem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_ordemActionPerformed(evt);
			}
		});

		jLabel31.setText("Ficha");

		jLabel32.setText("Finanças");

		jTextField_cozinha.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_cozinhaMouseClicked(evt);
			}
		});
		jTextField_cozinha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_cozinhaActionPerformed(evt);
			}
		});

		jTextField_acolhida.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_acolhidaMouseClicked(evt);
			}
		});
		jTextField_acolhida.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_acolhidaActionPerformed(evt);
			}
		});

		jLabel23.setText("Secretária");

		jTextField_vigilia.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_vigiliaMouseClicked(evt);
			}
		});
		jTextField_vigilia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_vigiliaActionPerformed(evt);
			}
		});

		jLabel12.setText("Diretor Espiritual");

		jTextField_recep.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_recepMouseClicked(evt);
			}
		});
		jTextField_recep.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_recepActionPerformed(evt);
			}
		});

		jLabel35.setText("Ano");

		jTextField_ano.setText(Integer.toString(encontro.getAno()));
		jLabel13.setText("Coordenador Geral");

		jTextField_padre.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_padreMouseClicked(evt);
			}
		});
		jTextField_padre.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_padreActionPerformed(evt);
			}
		});

		jTextField_ano.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_anoActionPerformed(evt);
			}
		});

		jLabel14.setText("Apresentador");

		jTextField_casalADM.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_casalADMActionPerformed(evt);
			}
		});

		jLabel15.setText("Canto");

		jTextField_ficha.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField_fichaMouseClicked(evt);
			}
		});
		jTextField_ficha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_fichaActionPerformed(evt);
			}
		});

		jLabel16.setText("Boa Vontade");

		jLabel17.setText("Recepção Palestra");

		jButton1.setText("REGISTRAR");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
		jLabel2.setText("EQUIPE DIRIGENTE");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(58, 58, 58)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel25).addComponent(jLabel13).addComponent(jLabel14)
								.addComponent(jLabel15).addComponent(jLabel16).addComponent(jLabel17)
								.addComponent(jLabel18).addComponent(jLabel12)
								.addComponent(jTextField_padre, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_apres, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_canto, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_boa, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_casalADM, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_recep, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_visit, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74,
								Short.MAX_VALUE)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup()
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel26).addComponent(jLabel29)
														.addComponent(jLabel22).addComponent(jLabel19)
														.addComponent(jLabel20).addComponent(jLabel21)
														.addComponent(jTextField_circulo,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_cafe,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_cozinha,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_ordem,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_liturgia,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_acolhida,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_vigilia,
																javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel28))
												.addComponent(
														jTextField_secret, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 200,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(44, 44, 44)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(jTextField_financas,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				200,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextField_ficha,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				200,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextField_pos,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				200,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextField_montag,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				200,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(jLabel34)
																						.addComponent(jLabel33)
																						.addComponent(jLabel32)
																						.addComponent(jLabel31))
																				.addGap(63, 63, 63)))
																.addComponent(jLabel35)
																.addComponent(jTextField_ano,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 200,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jButton1,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 154,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(24, 24, 24))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addComponent(jLabel2).addGap(39,
																39, 39))))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel23)
												.addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(9, 9, 9)
						.addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout
										.createSequentialGroup().addGroup(layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addComponent(jLabel22)
																.addGap(103, 103, 103).addComponent(jLabel20)
																.addGap(44, 44, 44).addComponent(jLabel19)
																.addGap(44, 44, 44).addComponent(jLabel26))
														.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
																.addComponent(jTextField_circulo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(27, 27, 27)
																.addComponent(jTextField_liturgia,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(27, 27, 27)
																.addComponent(jTextField_cafe,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(27, 27, 27)
																.addComponent(jTextField_cozinha,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(27, 27, 27).addComponent(jTextField_ordem,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup().addGap(59, 59, 59)
																.addComponent(jLabel21)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel28)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jTextField_vigilia,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(jLabel2).addGap(18, 18, 18).addComponent(jLabel32)
														.addGap(3, 3, 3)
														.addComponent(jTextField_financas,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel31)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_ficha,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel33)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_pos,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel34)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_montag,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel35)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_ano,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel29)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_acolhida,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel23)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_secret,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(6, 6, 6))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(139, 139, 139)
												.addComponent(jTextField_apres, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(27, 27, 27)
												.addComponent(jTextField_canto, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(27, 27, 27).addComponent(jTextField_boa,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel12)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField_padre, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel13)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField_casalADM,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel14).addGap(44, 44, 44).addComponent(jLabel15)
												.addGap(44, 44, 44).addComponent(jLabel16).addGap(44, 44, 44)
												.addComponent(jLabel17)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField_recep, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel18)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField_compras, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel25)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField_visit, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 38, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseEntered
		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel1MouseEntered

	private void jTextField_cantoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_cantoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_cantoActionPerformed

	private void jTextField_posActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_posActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_posActionPerformed

	private void jTextField_financasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_financasActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_financasActionPerformed

	private void jTextField_montagActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_montagActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_montagActionPerformed

	private void jTextField_circuloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_circuloActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_circuloActionPerformed

	private void jTextField_visitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_visitActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_visitActionPerformed

	private void jTextField_boaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_boaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_boaActionPerformed

	private void jTextField_apresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_apresActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_apresActionPerformed

	private void jTextField_secretActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_secretActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_secretActionPerformed

	private void jTextField_liturgiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_liturgiaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_liturgiaActionPerformed

	private void jTextField_cafeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_cafeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_cafeActionPerformed

	private void jTextField_comprasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_comprasActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_comprasActionPerformed

	private void jTextField_ordemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_ordemActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_ordemActionPerformed

	private void jTextField_cozinhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_cozinhaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_cozinhaActionPerformed

	private void jTextField_acolhidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_acolhidaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_acolhidaActionPerformed

	private void jTextField_vigiliaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_vigiliaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_vigiliaActionPerformed

	private void jTextField_recepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_recepActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_recepActionPerformed

	private void jTextField_padreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_padreActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_padreActionPerformed

	private void jTextField_anoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_anoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_anoActionPerformed

	private void jTextField_casalADMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_casalADMActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_casalADMActionPerformed

	private void jTextField_fichaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_fichaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_fichaActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		String diretorEspiritual, coordenadorGeral, apresentador, canto, boaVontade, recepcao, compras, visitacao,
				circulo, liturgia, miniMercado, cozinha, ordemLimpeza, vigilia, acolhida, secretaria, financas, ficha,
				posEncontro, montagemPalestra, ano;
		diretorEspiritual = jTextField_padre.getText();
		coordenadorGeral = jTextField_casalADM.getText();
		apresentador = jTextField_apres.getText();
		canto = jTextField_canto.getText();
		boaVontade = jTextField_boa.getText();
		recepcao = jTextField_recep.getText();
		compras = jTextField_compras.getText();
		visitacao = jTextField_visit.getText();
		circulo = jTextField_circulo.getText();
		liturgia = jTextField_liturgia.getText();
		miniMercado = jTextField_cafe.getText();
		cozinha = jTextField_cozinha.getText();
		ordemLimpeza = jTextField_ordem.getText();
		vigilia = jTextField_vigilia.getText();
		acolhida = jTextField_acolhida.getText();
		secretaria = jTextField_secret.getText();
		financas = jTextField_financas.getText();
		ficha = jTextField_ficha.getText();
		posEncontro = jTextField_pos.getText();
		montagemPalestra = jTextField_montag.getText();
		ano = jTextField_ano.getText();

		if (diretorEspiritual.equals("") || coordenadorGeral.equals("") || apresentador.equals("") || canto.equals("")
				|| boaVontade.equals("") || recepcao.equals("") || circulo.equals("") || liturgia.equals("")
				|| miniMercado.equals("") || compras.equals("") || visitacao.equals("") || cozinha.equals("")
				|| ordemLimpeza.equals("") || vigilia.equals("") || acolhida.equals("") || secretaria.equals("")
				|| financas.equals("") || ficha.equals("") || posEncontro.equals("") || montagemPalestra.equals("")
				|| ano.equals("")) {
			JOptionPane.showMessageDialog(null, "Preencha todos os campos");
		} else {
			dispose();
			JOptionPane.showMessageDialog(null, "Encontro cadastrado com sucesso");
			// envia as variaveis pro banco
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jTextField_padreMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_padreMouseClicked
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_padreMouseClicked

	private void jTextField_apresMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_apresMouseClicked
		Equipe equipe = gerarEquipeTipo("Apresentadores");
		telaEquipeEditavel(jTextField_apres, equipe);
	}// GEN-LAST:event_jTextField_apresMouseClicked

	private void jTextField_cantoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_cantoMouseClicked
		Equipe equipe = gerarEquipeTipo("Canto");
		telaEquipeEditavel(jTextField_canto, equipe);
	}// GEN-LAST:event_jTextField_cantoMouseClicked

	private void jTextField_boaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_boaMouseClicked
		Equipe equipe = gerarEquipeTipo("Boa Vontade");
		telaEquipeEditavel(jTextField_boa, equipe);
	}// GEN-LAST:event_jTextField_boaMouseClicked

	private void jTextField_recepMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_recepMouseClicked
		Equipe equipe = gerarEquipeTipo("Recepçao Palestra");
		telaEquipeEditavel(jTextField_recep, equipe);
	}// GEN-LAST:event_jTextField_recepMouseClicked

	private void jTextField_comprasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_comprasMouseClicked
		Equipe equipe = gerarEquipeTipo("Compras");
		telaEquipeEditavel(jTextField_compras, equipe);
	}// GEN-LAST:event_jTextField_comprasMouseClicked

	private void jTextField_visitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_visitMouseClicked
		Equipe equipe = gerarEquipeTipo("Visitaçao");
		telaEquipeEditavel(jTextField_visit, equipe);
	}// GEN-LAST:event_jTextField_visitMouseClicked

	private void jTextField_circuloMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_circuloMouseClicked
		Equipe equipe = gerarEquipeTipo("Circulo Estudo");
		telaEquipeEditavel(jTextField_circulo, equipe);
	}// GEN-LAST:event_jTextField_circuloMouseClicked

	private void jTextField_liturgiaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_liturgiaMouseClicked
		Equipe equipe = gerarEquipeTipo("Liturgia");
		telaEquipeEditavel(jTextField_liturgia, equipe);
	}// GEN-LAST:event_jTextField_liturgiaMouseClicked

	private void jTextField_cafeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_cafeMouseClicked
		Equipe equipe = gerarEquipeTipo("MiniMercado & Cafe");
		telaEquipeEditavel(jTextField_cafe, equipe);
	}// GEN-LAST:event_jTextField_cafeMouseClicked

	private void jTextField_cozinhaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_cozinhaMouseClicked
		Equipe equipe = gerarEquipeTipo("Cozinha");
		telaEquipeEditavel(jTextField_cozinha, equipe);
	}// GEN-LAST:event_jTextField_cozinhaMouseClicked

	private void jTextField_ordemMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_ordemMouseClicked
		Equipe equipe = gerarEquipeTipo("Ordem & Limpeza");
		telaEquipeEditavel(jTextField_ordem, equipe);
	}// GEN-LAST:event_jTextField_ordemMouseClicked

	private void jTextField_vigiliaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_vigiliaMouseClicked
		Equipe equipe = gerarEquipeTipo("Vigilia");
		telaEquipeEditavel(jTextField_vigilia, equipe);
	}// GEN-LAST:event_jTextField_vigiliaMouseClicked

	private void jTextField_acolhidaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_acolhidaMouseClicked
		Equipe equipe = gerarEquipeTipo("Acolhida");
		telaEquipeEditavel(jTextField_acolhida, equipe);
	}// GEN-LAST:event_jTextField_acolhidaMouseClicked

	private void jTextField_secretMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_secretMouseClicked
		Equipe equipe = gerarEquipeTipo("Secretaria");
		telaEquipeEditavel(jTextField_secret, equipe);
	}// GEN-LAST:event_jTextField_secretMouseClicked

	private void jTextField_financasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_financasMouseClicked
		Equipe equipe = gerarEquipeTipo("Finanças");
		telaEquipeEditavel(jTextField_financas, equipe);
	}// GEN-LAST:event_jTextField_financasMouseClicked

	private void jTextField_fichaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_fichaMouseClicked
		Equipe equipe = gerarEquipeTipo("Ficha");
		telaEquipeEditavel(jTextField_ficha, equipe);
	}// GEN-LAST:event_jTextField_fichaMouseClicked

	private void jTextField_posMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_posMouseClicked
		Equipe equipe = gerarEquipeTipo("Pos Encontro");
		telaEquipeEditavel(jTextField_pos, equipe);
	}// GEN-LAST:event_jTextField_posMouseClicked

	private void jTextField_montagMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField_montagMouseClicked
		Equipe equipe = gerarEquipeTipo("Montagem & Palestra");
		telaEquipeEditavel(jTextField_montag, equipe);
	}// GEN-LAST:event_jTextField_montagMouseClicked

	telaHistorico obj = new telaHistorico();

	public void telaEquipeEditavel(JTextField campo, Equipe equipe) {
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadastroEncontros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadastroEncontros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadastroEncontros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadastroEncontros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new CadastroEncontros().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	public Equipe gerarEquipeTipo(String tituloTipoEquipe) {
		Equipe equipe = new Equipe();
		TipoEquipe tipoEquipe = new TipoEquipe();
		try {
			BaseDAO baseDAO = new BaseDAO();
			TipoEquipeDAO tipoEquipeDAO = new TipoEquipeDAOImp(baseDAO);
			tipoEquipe = tipoEquipeDAO.buscarPorNome(tituloTipoEquipe);
			tipoEquipeDAO.getConnectionSource().close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		equipe.setTipoEquipe(tipoEquipe);
		equipe.setAno(encontro.getAno());
		return equipe;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JPanel jPanel1;
	public javax.swing.JTextField jTextField_acolhida;
	public javax.swing.JTextField jTextField_ano;
	public javax.swing.JTextField jTextField_apres;
	public javax.swing.JTextField jTextField_boa;
	public javax.swing.JTextField jTextField_cafe;
	public javax.swing.JTextField jTextField_canto;
	public javax.swing.JTextField jTextField_casalADM;
	public javax.swing.JTextField jTextField_circulo;
	public javax.swing.JTextField jTextField_compras;
	public javax.swing.JTextField jTextField_cozinha;
	public javax.swing.JTextField jTextField_ficha;
	public javax.swing.JTextField jTextField_financas;
	public javax.swing.JTextField jTextField_liturgia;
	public javax.swing.JTextField jTextField_montag;
	public javax.swing.JTextField jTextField_ordem;
	public javax.swing.JTextField jTextField_padre;
	public javax.swing.JTextField jTextField_pos;
	public javax.swing.JTextField jTextField_recep;
	public javax.swing.JTextField jTextField_secret;
	public javax.swing.JTextField jTextField_vigilia;
	public javax.swing.JTextField jTextField_visit;
	// End of variables declaration//GEN-END:variables
}
