/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author raquelmelo
 */
public class telaHistorico extends javax.swing.JFrame {

    /**
     * Creates new form telaHistorico
     */
    public telaHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_boa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_visit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_ficha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_casalADM = new javax.swing.JTextField();
        jTextField_circulo = new javax.swing.JTextField();
        jTextField_cozinha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField_montag = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_financas = new javax.swing.JTextField();
        jTextField_ordem = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField_pos = new javax.swing.JTextField();
        jTextField_compras = new javax.swing.JTextField();
        jTextField_canto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField_cafe = new javax.swing.JTextField();
        jTextField_liturgia = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField_acolhida = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_secret = new javax.swing.JTextField();
        jTextField_apres = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_ano = new javax.swing.JTextField();
        jTextField_padre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField_recep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_vigilia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 187, 125));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(27, 187, 125));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField_boa.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_boa.setEnabled(false);
        jTextField_boa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_boaMouseClicked(evt);
            }
        });
        jTextField_boa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_boaActionPerformed(evt);
            }
        });

        jLabel19.setText("Cozinha");

        jTextField_visit.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_visit.setEnabled(false);
        jTextField_visit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_visitMouseClicked(evt);
            }
        });
        jTextField_visit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_visitActionPerformed(evt);
            }
        });

        jLabel20.setText("Mini Mercado e Café");

        jTextField_ficha.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_ficha.setEnabled(false);
        jTextField_ficha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_fichaMouseClicked(evt);
            }
        });
        jTextField_ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fichaActionPerformed(evt);
            }
        });

        jLabel15.setText("Canto");

        jLabel21.setText("Liturgia");

        jTextField_casalADM.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_casalADM.setEnabled(false);
        jTextField_casalADM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_casalADMMouseClicked(evt);
            }
        });
        jTextField_casalADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_casalADMActionPerformed(evt);
            }
        });

        jTextField_circulo.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_circulo.setEnabled(false);
        jTextField_circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_circuloMouseClicked(evt);
            }
        });
        jTextField_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_circuloActionPerformed(evt);
            }
        });

        jTextField_cozinha.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_cozinha.setEnabled(false);
        jTextField_cozinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cozinhaMouseClicked(evt);
            }
        });
        jTextField_cozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cozinhaActionPerformed(evt);
            }
        });

        jLabel14.setText("Apresentador");

        jLabel22.setText("Circulo Estudo");

        jLabel32.setText("Finanças");

        jTextField_montag.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_montag.setEnabled(false);
        jTextField_montag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_montagMouseClicked(evt);
            }
        });
        jTextField_montag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_montagActionPerformed(evt);
            }
        });

        jLabel25.setText("Visitação");

        jLabel31.setText("Ficha");

        jTextField_financas.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_financas.setEnabled(false);
        jTextField_financas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_financasMouseClicked(evt);
            }
        });
        jTextField_financas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_financasActionPerformed(evt);
            }
        });

        jTextField_ordem.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_ordem.setEnabled(false);
        jTextField_ordem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ordemMouseClicked(evt);
            }
        });
        jTextField_ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ordemActionPerformed(evt);
            }
        });

        jLabel17.setText("Recepção Palestra");

        jLabel16.setText("Boa Vontade");

        jLabel18.setText("Compras");

        jLabel33.setText("Pós Encontro");

        jTextField_pos.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_pos.setEnabled(false);
        jTextField_pos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_posMouseClicked(evt);
            }
        });
        jTextField_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_posActionPerformed(evt);
            }
        });

        jTextField_compras.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_compras.setEnabled(false);
        jTextField_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_comprasMouseClicked(evt);
            }
        });
        jTextField_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_comprasActionPerformed(evt);
            }
        });

        jTextField_canto.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_canto.setEnabled(false);
        jTextField_canto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cantoMouseClicked(evt);
            }
        });
        jTextField_canto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cantoActionPerformed(evt);
            }
        });

        jLabel34.setText("Montagem e Palestra");

        jTextField_cafe.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_cafe.setEnabled(false);
        jTextField_cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cafeMouseClicked(evt);
            }
        });
        jTextField_cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cafeActionPerformed(evt);
            }
        });

        jTextField_liturgia.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_liturgia.setEnabled(false);
        jTextField_liturgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_liturgiaMouseClicked(evt);
            }
        });
        jTextField_liturgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_liturgiaActionPerformed(evt);
            }
        });

        jLabel23.setText("Secretária");

        jTextField_acolhida.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_acolhida.setEnabled(false);
        jTextField_acolhida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_acolhidaMouseClicked(evt);
            }
        });
        jTextField_acolhida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_acolhidaActionPerformed(evt);
            }
        });

        jLabel29.setText("Acolhida");

        jLabel28.setText("Vigilia na Comunidade");

        jTextField_secret.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_secret.setEnabled(false);
        jTextField_secret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_secretMouseClicked(evt);
            }
        });
        jTextField_secret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_secretActionPerformed(evt);
            }
        });

        jTextField_apres.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_apres.setEnabled(false);
        jTextField_apres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_apresMouseClicked(evt);
            }
        });
        jTextField_apres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apresActionPerformed(evt);
            }
        });

        jLabel26.setText("Ordem e Limpeza");

        jTextField_ano.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_ano.setEnabled(false);
        jTextField_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_anoActionPerformed(evt);
            }
        });

        jTextField_padre.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_padre.setEnabled(false);
        jTextField_padre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_padreMouseClicked(evt);
            }
        });
        jTextField_padre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_padreActionPerformed(evt);
            }
        });

        jLabel13.setText("Coordenador Geral");

        jLabel35.setText("Ano");

        jTextField_recep.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_recep.setEnabled(false);
        jTextField_recep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_recepMouseClicked(evt);
            }
        });
        jTextField_recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_recepActionPerformed(evt);
            }
        });

        jLabel12.setText("Diretor Espiritual");

        jTextField_vigilia.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField_vigilia.setEnabled(false);
        jTextField_vigilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_vigiliaMouseClicked(evt);
            }
        });
        jTextField_vigilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_vigiliaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("EQUIPE DIRIGENTE");

        jButton1.setText("Imprimir");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_padre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_apres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_canto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_boa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_casalADM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_recep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_visit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jTextField_circulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cafe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ordem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_liturgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_acolhida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_vigilia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel32)
                                        .addComponent(jTextField_financas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33)
                                        .addComponent(jTextField_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel34))
                                    .addComponent(jTextField_montag, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jTextField_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jTextField_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextField_liturgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextField_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel21)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ordem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_vigilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jTextField_financas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_ficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_montag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel32))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_acolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_secret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jTextField_apres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField_canto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField_boa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_casalADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel15)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel16)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_recep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_visit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_boaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_boaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_boaActionPerformed

    private void jTextField_visitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_visitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_visitActionPerformed

    private void jTextField_fichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fichaActionPerformed

    private void jTextField_casalADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_casalADMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_casalADMActionPerformed

    private void jTextField_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_circuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_circuloActionPerformed

    private void jTextField_cozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cozinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cozinhaActionPerformed

    private void jTextField_montagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_montagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_montagActionPerformed

    private void jTextField_financasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_financasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_financasActionPerformed

    private void jTextField_ordemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ordemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ordemActionPerformed

    private void jTextField_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_posActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posActionPerformed

    private void jTextField_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_comprasActionPerformed

    private void jTextField_cantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cantoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cantoActionPerformed

    private void jTextField_cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cafeActionPerformed

    private void jTextField_liturgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_liturgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_liturgiaActionPerformed

    private void jTextField_acolhidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_acolhidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_acolhidaActionPerformed

    private void jTextField_secretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_secretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_secretActionPerformed

    private void jTextField_apresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apresActionPerformed

    private void jTextField_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_anoActionPerformed

    private void jTextField_padreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_padreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_padreActionPerformed

    private void jTextField_recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_recepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_recepActionPerformed

    private void jTextField_vigiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_vigiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_vigiliaActionPerformed

    private void jTextField_padreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_padreMouseClicked
        
    }//GEN-LAST:event_jTextField_padreMouseClicked

    private void jTextField_casalADMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_casalADMMouseClicked
        telaEquipe(jTextField_casalADM);
    }//GEN-LAST:event_jTextField_casalADMMouseClicked

    private void jTextField_apresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_apresMouseClicked
        telaEquipe(jTextField_apres);
    }//GEN-LAST:event_jTextField_apresMouseClicked

    private void jTextField_cantoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cantoMouseClicked
        telaEquipe(jTextField_canto);
    }//GEN-LAST:event_jTextField_cantoMouseClicked

    private void jTextField_boaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_boaMouseClicked
        telaEquipe(jTextField_boa);
    }//GEN-LAST:event_jTextField_boaMouseClicked

    private void jTextField_recepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_recepMouseClicked
        telaEquipe(jTextField_recep);
    }//GEN-LAST:event_jTextField_recepMouseClicked

    private void jTextField_comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_comprasMouseClicked
        telaEquipe(jTextField_compras);
    }//GEN-LAST:event_jTextField_comprasMouseClicked

    private void jTextField_visitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_visitMouseClicked
        telaEquipe(jTextField_visit);
    }//GEN-LAST:event_jTextField_visitMouseClicked

    private void jTextField_circuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_circuloMouseClicked
        telaEquipe(jTextField_circulo);
    }//GEN-LAST:event_jTextField_circuloMouseClicked

    private void jTextField_liturgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_liturgiaMouseClicked
        telaEquipe(jTextField_liturgia);
    }//GEN-LAST:event_jTextField_liturgiaMouseClicked

    private void jTextField_cafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cafeMouseClicked
        telaEquipe(jTextField_cafe);
    }//GEN-LAST:event_jTextField_cafeMouseClicked

    private void jTextField_cozinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cozinhaMouseClicked
        telaEquipe(jTextField_cozinha);
    }//GEN-LAST:event_jTextField_cozinhaMouseClicked

    private void jTextField_ordemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ordemMouseClicked
        telaEquipe(jTextField_ordem);
    }//GEN-LAST:event_jTextField_ordemMouseClicked

    private void jTextField_vigiliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_vigiliaMouseClicked
        telaEquipe(jTextField_vigilia);
    }//GEN-LAST:event_jTextField_vigiliaMouseClicked

    private void jTextField_acolhidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_acolhidaMouseClicked
        telaEquipe(jTextField_acolhida);
    }//GEN-LAST:event_jTextField_acolhidaMouseClicked

    private void jTextField_secretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_secretMouseClicked
        telaEquipe(jTextField_secret);
    }//GEN-LAST:event_jTextField_secretMouseClicked

    private void jTextField_financasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_financasMouseClicked
        telaEquipe(jTextField_financas);
    }//GEN-LAST:event_jTextField_financasMouseClicked

    private void jTextField_fichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_fichaMouseClicked
        telaEquipe(jTextField_ficha);
    }//GEN-LAST:event_jTextField_fichaMouseClicked

    private void jTextField_posMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_posMouseClicked
        telaEquipe(jTextField_pos);
    }//GEN-LAST:event_jTextField_posMouseClicked

    private void jTextField_montagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_montagMouseClicked
        telaEquipe(jTextField_montag);
    }//GEN-LAST:event_jTextField_montagMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void telaEquipe(JTextField campo){
        telaEquipe obj = new telaEquipe();
        String apelido = campo.getText();
        DefaultTableModel model2 = (DefaultTableModel) obj.jTable1.getModel();
        if (model2.getRowCount() > 0) {
            for (int i = model2.getRowCount() - 1; i > -1; i--) {
                model2.removeRow(i);
            }
        }
        //busca no banco o correspondente pelo apelido naquele ano e quem é a equipe dele para preencher a tabela
        Object[] linha = new Object[10];
        for (int i=0;i<5;i++){
            linha[0] = apelido;
            linha[1] = "funcao";
            model2.addRow(linha);
        }
        obj.setVisible(true);
        obj.pack();
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField_acolhida;
    public javax.swing.JTextField jTextField_ano;
    public javax.swing.JTextField jTextField_apres;
    public javax.swing.JTextField jTextField_boa;
    public javax.swing.JTextField jTextField_cafe;
    public javax.swing.JTextField jTextField_canto;
    public javax.swing.JTextField jTextField_casalADM;
    public javax.swing.JTextField jTextField_circulo;
    public javax.swing.JTextField jTextField_compras;
    public javax.swing.JTextField jTextField_cozinha;
    public javax.swing.JTextField jTextField_ficha;
    public javax.swing.JTextField jTextField_financas;
    public javax.swing.JTextField jTextField_liturgia;
    public javax.swing.JTextField jTextField_montag;
    public javax.swing.JTextField jTextField_ordem;
    public javax.swing.JTextField jTextField_padre;
    public javax.swing.JTextField jTextField_pos;
    public javax.swing.JTextField jTextField_recep;
    public javax.swing.JTextField jTextField_secret;
    public javax.swing.JTextField jTextField_vigilia;
    public javax.swing.JTextField jTextField_visit;
    // End of variables declaration//GEN-END:variables
}
