/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.IOException;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;

import dao.BaseDAO;
import dao.UsuarioDAO;
import dao.UsuarioDAOImp;
import entity.Usuario;

/**
 *
 * @author raquelmelo
 */
public class telaCadastro extends javax.swing.JFrame {

	/**
	 * Creates new form telaCadastro
	 */
	public telaCadastro() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField_apelido = new javax.swing.JTextField();
		jTextField_email = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPasswordField_senha = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(27, 187, 125));
		jPanel1.setForeground(new java.awt.Color(0, 0, 0));

		jLabel1.setBackground(new java.awt.Color(253, 31, 64));
		jLabel1.setFont(new java.awt.Font("Latin Modern Math", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(254, 254, 254));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Cadastro");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0,
								Short.MAX_VALUE)));

		jTextField_apelido.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_apelidoActionPerformed(evt);
			}
		});

		jTextField_email.setToolTipText("");

		jButton1.setText("Cadastrar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
		jLabel2.setText("Apelido");

		jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
		jLabel3.setText("E-mail");

		jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
		jLabel4.setText("Senha");

		jPasswordField_senha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField_senhaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2).addComponent(jLabel3)))
								.addGroup(layout.createSequentialGroup().addGap(9, 9, 9).addComponent(jLabel4)))
						.addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jTextField_apelido)
								.addComponent(jTextField_email, javax.swing.GroupLayout.DEFAULT_SIZE, 299,
										Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 145,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPasswordField_senha))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(54, 54, 54)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addComponent(jLabel2).addGap(42, 42, 42).addComponent(jLabel3)
						.addGap(38, 38, 38)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)
								.addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(98, 98, 98).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(0, 17, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField_apelidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_apelidoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_apelidoActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_jButton1ActionPerformed
		String apelido, email, senha;
		apelido = jTextField_apelido.getText();
		email = jTextField_email.getText();
		senha = jPasswordField_senha.getText();
		if (apelido.equals("") || email.equals("") || senha.equals("")) {
			JOptionPane.showMessageDialog(null, "Preencha todos os campos");
		} else {
			Usuario user = new Usuario();
			user.setNomeUsual(apelido);
			user.setEmail(email);
			user.setSenha(senha);
			BaseDAO base;
			try {
				base = new BaseDAO();
				UsuarioDAO userDAO = new UsuarioDAOImp(base);
				userDAO.create(user);
				userDAO.getConnectionSource().close();
				dispose();
				JOptionPane.showMessageDialog(null, apelido + " cadastrado(a) com sucesso!");
			} catch (SQLException e) {
				dispose();
				JOptionPane.showMessageDialog(null,
						"Ocorreu um erro ao tentar salvar! Verifique se todos os campos foram preenchidos corretamente!");
			}
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jPasswordField_senhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField_senhaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jPasswordField_senhaActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField_senha;
	private javax.swing.JTextField jTextField_apelido;
	private javax.swing.JTextField jTextField_email;
	// End of variables declaration//GEN-END:variables

}
